import turtle as tortue

def case():
    for i in range(2):
        tortue.down()
        tortue.forward(75)
        tortue.right(90)
        tortue.forward(15)
        tortue.right(90)
        tortue.up()

def colonne():
    for i in range(19):
        case()
        tortue.right(90)
        tortue.forward(15)
        tortue.left(90)


def colonne1():
    tortue.goto(-300,200)
    colonne()

def colonne2():
    tortue.goto(-225,200)
    colonne()

def colonne3():
    tortue.goto(-150,200)
    colonne()

def ecriture():
    tortue.goto(-300,200)
    tortue.forward(5)
    tortue.right(90)
    tortue.forward(15)
    tortue.down()
    tortue.write("Scores", font=("arial", 10, 'bold'))
    tortue.up()
    tortue.forward(15)
    tortue.down()
    tortue.write("Les 1", font=("arial", 10, 'normal'))
    tortue.up()
    tortue.forward(15)
    tortue.down()
    tortue.write("Les 2", font=("arial", 10, 'normal'))
    tortue.up()
    tortue.forward(15)
    tortue.down()
    tortue.write("Les 3", font=("arial", 10, 'normal'))
    tortue.up()
    tortue.forward(15)
    tortue.down()
    tortue.write("Les 4", font=("arial", 10, 'normal'))
    tortue.up()
    tortue.forward(15)
    tortue.down()
    tortue.write("Les 5", font=("arial", 10, 'normal'))
    tortue.up()
    tortue.forward(15)
    tortue.down()
    tortue.write("Les 6", font=("arial", 10, 'normal'))
    tortue.up()
    tortue.forward(15)
    tortue.down()
    tortue.write("Tot. chiffres", font=("arial", 10, 'normal'))
    tortue.up()
    tortue.forward(15)
    tortue.down()
    tortue.write("Bonus", font=("arial", 10, 'normal'))
    tortue.up()
    tortue.forward(15)
    tortue.down()
    tortue.write("S. min", font=("arial", 10, 'normal'))
    tortue.up()
    tortue.forward(15)
    tortue.down()
    tortue.write("S. max", font=("arial", 10, 'normal'))
    tortue.up()
    tortue.forward(15)
    tortue.down()
    tortue.write("Bonus", font=("arial", 10, 'normal'))
    tortue.up()
    tortue.forward(15)
    tortue.down()
    tortue.write("Petite suite", font=("arial", 10, 'normal'))
    tortue.up()
    tortue.forward(15)
    tortue.down()
    tortue.write("Grde suite", font=("arial", 10, 'normal'))
    tortue.up()
    tortue.forward(15)
    tortue.down()
    tortue.write("Brelan", font=("arial", 10, 'normal'))
    tortue.up()
    tortue.forward(15)
    tortue.down()
    tortue.write("Full", font=("arial", 10, 'normal'))
    tortue.up()
    tortue.forward(15)
    tortue.down()
    tortue.write("Carré", font=("arial", 10, 'normal'))
    tortue.up()
    tortue.forward(15)
    tortue.down()
    tortue.write("Yam", font=("arial", 10, 'normal'))
    tortue.up()
    tortue.forward(15)
    tortue.down()
    tortue.write("Total", font=("arial", 10, 'bold'))

def name(place, bot, number):
    tortue.up()
    #tortue.left(90)
    tortue.right(2*90)
    if place == 1 : tortue.goto(-225,200)
    else : tortue.goto(-150,200)
    tortue.forward(5)
    tortue.right(90)
    tortue.forward(15)
    tortue.right(90)
    tortue.forward(20)
    tortue.down()
    if bot == False : tmp = "Joueur N" + str(number)
    else : tmp = "Bot N" + str(number)
    tortue.write(tmp, font=("arial", 10, 'bold'))
    tortue.left(90)

def colonne_joueur(player):
    tortue.forward(5)
    tortue.right(90)
    tortue.forward(30)
    tortue.down()
    if player.Co1 > 0:
        tortue.write(player.Co1, font=("arial", 10, 'normal'))
    tortue.up()
    tortue.forward(15)
    tortue.down()
    if player.Co2 > 0:
        tortue.write(player.Co2, font=("arial", 10, 'normal'))
    tortue.up()
    tortue.forward(15)
    tortue.down()
    if player.Co3 > 0:
        tortue.write(player.Co3, font=("arial", 10, 'normal'))
    tortue.up()
    tortue.forward(15)
    tortue.down()
    if player.Co4 > 0:
        tortue.write(player.Co4, font=("arial", 10, 'normal'))
    tortue.up()
    tortue.forward(15)
    tortue.down()
    if player.Co5 > 0:
        tortue.write(player.Co5, font=("arial", 10, 'normal'))
    tortue.up()
    tortue.forward(15)
    tortue.down()
    if player.Co6 > 0:
        tortue.write(player.Co6, font=("arial", 10, 'normal'))
    tortue.up()
    tortue.forward(15)
    tortue.down()
    tortue.write(player.Co1+player.Co2+player.Co3+player.Co4+player.Co5+player.Co6, font=("arial", 10, 'normal'))
    tortue.up()
    tortue.forward(15)
    tortue.down()
    if player.Bonus == True:
        tortue.write("30", font=("arial", 10, 'normal'))
    tortue.up()
    tortue.forward(15)
    tortue.down()
    if player.Mini > 0:
        tortue.write(player.Mini, font=("arial", 10, 'normal'))
    tortue.up()
    tortue.forward(15)
    tortue.down()
    if player.Maxi > 0:
        tortue.write(player.Maxi, font=("arial", 10, 'normal'))
    tortue.up()
    tortue.forward(15)
    tortue.down()
    tortue.write(player.Co1*(player.Maxi-player.Mini), font=("arial", 10, 'normal'))
    tortue.up()
    tortue.forward(15)
    tortue.down()
    if player.PS == True:
        tortue.write("20", font=("arial", 10, 'normal'))
    tortue.up()
    tortue.forward(15)
    tortue.down()
    if player.GS == True:
        tortue.write("30", font=("arial", 10, 'normal'))
    tortue.up()
    tortue.forward(15)
    tortue.down()
    if player.Brelan == True:
        tortue.write("20", font=("arial", 10, 'normal'))
    tortue.up()
    tortue.forward(15)
    tortue.down()
    if player.Full == True:
        tortue.write("30", font=("arial", 10, 'normal'))
    tortue.up()
    tortue.forward(15)
    tortue.down()
    if player.Carre == True:
        tortue.write("40", font=("arial", 10, 'normal'))
    tortue.up()
    tortue.forward(15)
    tortue.down()
    if player.Yam == True:
        tortue.write("50", font=("arial", 10, 'normal'))
    tortue.up()
    tortue.forward(15)
    tortue.down()
    tortue.write(player.Total, font=("arial", 10, 'normal'))
